### ISSUE TITLE
Greenscreen

### ISSUE THREAD

**Issue by druide1976** [einfall/serienrecorder#53]
Schon beim starten des Plugins kommt ein Greenscreen:
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/enigma.py", line 6579, in __call__
    return ret(*args, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 295, in processDelay
    callback(*retval)
  File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorder.py", line 10255, in checkForUpdate
    self.startScreen()
  File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorder.py", line 10507, in startScreen
    self.readWebpage(False)
  File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorder.py", line 10533, in readWebpage
    self.processPlanerData(planerData, False)
  File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorder.py", line 10540, in processPlanerData
    headDate = [data["date"]]
KeyError: 'date'
[enigma2_crash_1482498473.log.txt](https://github.com/einfall/serienrecorder/files/670892/enigma2_crash_1482498473.log.txt)

Kann ich etwas tun um das Problem zu lösen?

**Comment by MacDisein** [comment]
Einfach die akuellen Sourcen von GitHub verwenden, dort ist der Fehler behoben (Version 3.3.1-beta)

**Comment by druide1976** [comment]
Ups, sorry
Nicht gesehen

Danke und Schöne Feiertage

Am 23.12.2016 15:14 schrieb "MacDisein" <notifications@github.com>:
