### ISSUE TITLE
Greenscreen beim "Serie suchen" 3.4.0-beta

### ISSUE THREAD

**Issue by druide1976** [einfall/serienrecorder#55]
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/enigma.py", line 6579, in __call__
    return ret(*args, **kwargs)
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 51, in action
    res = self.actions[action]()
  File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorder.py", line 5680, in searchSeries
    self.session.openWithCallback(self.wSearch, NTIVirtualKeyBoard, title = "Serien Titel eingeben:")
  File "/usr/lib/enigma2/python/mytest.py", line 424, in openWithCallback
    dlg = self.open(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 452, in open
    dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 353, in instantiateDialog
    return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
  File "/usr/lib/enigma2/python/mytest.py", line 395, in doInstantiateDialog
    dlg.applySkin()
  File "/usr/lib/enigma2/python/Components/GUISkin.py", line 119, in applySkin
    self.createGUIScreen(self.instance, self.desktop)
  File "/usr/lib/enigma2/python/Components/GUISkin.py", line 48, in createGUIScreen
    applyAllAttributes(w.instance, desktop, w.skinAttributes, self.scale)
  File "/usr/lib/enigma2/python/skin.py", line 343, in applyAllAttributes
    applySingleAttribute(guiObject, desktop, attrib, value, scale)
  File "/usr/lib/enigma2/python/skin.py", line 208, in applySingleAttribute
    ptr = loadPixmap(value, desktop) # this should already have been filename-resolved.
  File "/usr/lib/enigma2/python/skin.py", line 187, in loadPixmap
    raise SkinError("pixmap file %s not found!" % (path))
skin.SkinError: {newnigma2-HD/skin.xml}: pixmap file /usr/share/enigma2/newnigma2-HD/skin_default/vkey_text.png not found!
[enigma2_crash_1482837812.log.txt](https://github.com/einfall/serienrecorder/files/674075/enigma2_crash_1482837812.log.txt)

**Comment by egn1** [comment]
Die Ursache muss irgendwie am verwendeten Skin liegen. Probiere es bitte mal mit einem anderen Skin aus.

**Comment by druide1976** [comment]
Stimmt, mit Original Dream-Skin kein Greenscreen mehr. Danke!
Serien werden zwar mit der Suche keine gefunden, aber das ist ja zur Zeit leider so.

Guten Rutsch!
