### ISSUE TITLE
[4.5.3-Beta] Erstellt keine Timer

### ISSUE THREAD

**Issue by MegaV0lt** [einfall/serienrecorder#95]
![Auswahl_161](https://user-images.githubusercontent.com/2804301/189851128-ee527001-7608-4e30-9708-fab4de0cae17.png)

Leider funktioniert der Serienrecorder bei mir nicht. Ich habe einige Serienmarker erstellt, aber es werden keine Timer angelegt. Auch das manuelle anlegen klappt nicht.

Auszug aus dem Crashlog

```
openATV Enigma2 crash log

crashdate=Di Sep 13 10:01:06 2022
compiledate=Sep 11 2022
skin=MetrixHD/skin.MySkin.xml
sourcedate=2022-09-10
branch=7.0
rev=31737+ab255a0
component=Enigma2

stbmodel=e4hd
stbmodel=e4hd
kernelcmdline=brcm_cma=504M@264M brcm_cma=192M@768M brcm_cma=1024M@2048M root=/dev/mmcblk0p8 rootsubdir=linuxrootfs3 kernel=/dev/mmcblk0p5 rw rootwait 8100s_4.boxmode=5 brcm_cma=504M@264M brcm_cma=192M@768M brcm_cma=1024M@2048M console=ttyS0,115200
nimsockets=NIM Socket 0:
imageversion=box_type=e4hdultra
imageissue=Welcome to openATV for %h
...
10:01:06.0216 Traceback (most recent call last):
10:01:06.0217   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 238, in action
10:01:06.0224   File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorderTransmissionsScreen.py", line 669, in keyGreen
10:01:06.0244     self.changesMade = self.getTimes()
10:01:06.0245   File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorderTransmissionsScreen.py", line 377, in getTimes
10:01:06.0254     (activatedTimer, deactivatedTimer) = serienRecSendeTermine.prepareTimer(self.database, self.filterMode, self.seriesWLID, self.seriesFSID, self.sendetermine_list)
10:01:06.0255   File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorderTransmissionsScreen.py", line 570, in prepareTimer
10:01:06.0266     (count_manually, count_primary_bouquet, count_secondary_bouquet) = database.getNumberOfTimersByBouquet(fsid, str(staffel), str(episode))
10:01:06.0266   File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorderDatabase.py", line 1241, in getNumberOfTimersByBouquet
10:01:06.0285     if primary_bouquet > 0:
10:01:06.0286 TypeError: '>' not supported between instances of 'NoneType' and 'int'
10:01:06.0287 [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.HelpableActionMap object at 0xae7852c8>>,('SerienRecorderActions', 'green')) failed)
```

**Comment by MacDisein** [comment]
Das ist wieder ein anderer Fehler - muss ich mir ansehen.

**Comment by MegaV0lt** [comment]
Vielleicht hilft das: https://stackoverflow.com/questions/43708541/python-typeerror-typeerror-not-supported-between-instances-of-nonetype

**Comment by MegaV0lt** [comment]
Ich denke hier kracht es
https://github.com/einfall/serienrecorder/blob/91e220c8939d916a4a4160ba48f876a2cd3ccbba/src/SerienRecorderDatabase.py#L1241

Meine Datenbank ist leer. Der Wert könnte also None sein. Bei jemanden mit Daten in der Datenbank funktioniert das wahrscheinlich.

PS: Nur eine Vermutung von mir. Bin kein Programmiere

**Comment by MacDisein** [comment]
Wenn keine Sender zugeordnet sind, dann hast du ein generelles Problem beim Anlegen von Timern.

**Comment by MegaV0lt** [comment]
![Auswahl_162](https://user-images.githubusercontent.com/2804301/189892504-fd289043-1027-4922-bfed-8b432f671fa6.png)
![Auswahl_163](https://user-images.githubusercontent.com/2804301/189892646-415571f3-f5fc-4377-a556-77dbd5dce1de.png)

**Comment by MacDisein** [comment]
Kannst du bitte mal das Debuglog im openATV aktivieren und dann noch einmal versuchen den Timer anzulegen, das Log dann bitte per Mail schicken.

**Comment by MegaV0lt** [comment]
Hallo, hier mal der Auszug vom Serienrecorder aus dem DEBUG-Log:

```
07:41:35.1337 [SerienRecorder] Initialize checkForRecording manual: False (with TV-Planer: False)
07:41:40.5609 "::ffff:192.168.178.20" - - [14/Sep/2022:05:41:38 +0000] "GET /serienrecorderui HTTP/1.1" 302 214 "http://e4hdultra/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:41:40.5933 "::ffff:192.168.178.20" - - [14/Sep/2022:05:41:40 +0000] "GET /serienrecorderui/ HTTP/1.1" 200 759 "http://e4hdultra/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:41:40.8024 "::ffff:192.168.178.20" - - [14/Sep/2022:05:41:40 +0000] "GET /serienrecorderui/assets/index.eb1ed97a.css HTTP/1.1" 200 260443 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:41:41.4943 "::ffff:192.168.178.20" - - [14/Sep/2022:05:41:40 +0000] "GET /serienrecorderui/assets/index.ec6f6fe4.js HTTP/1.1" 200 1282677 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:41:41.7626 "::ffff:192.168.178.20" - - [14/Sep/2022:05:41:41 +0000] "GET /serienrecorderui/assets/Home.ad3717f0.css HTTP/1.1" 200 159 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:41:41.7906 "::ffff:192.168.178.20" - - [14/Sep/2022:05:41:41 +0000] "GET /serienrecorderui/assets/logo.10553759.png HTTP/1.1" 200 8413 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:41:41.7921 Timing out client: IPv6Address(type='TCP', host='::ffff:192.168.178.20', port=45340, flowInfo=0, scopeID=0)
07:41:41.8169 [SerienRecorder] ApiGetInfo
07:41:41.8171 {}
07:41:41.9783 [SerienRecorder] ApiBaseResource (returnResult)
07:41:41.9787 [SerienRecorder] URI: [/serienrecorderapi/info] / Args: [{}] / Content: [] 
07:41:41.9830 "::ffff:192.168.178.20" - - [14/Sep/2022:05:41:41 +0000] "GET /serienrecorderapi/info HTTP/1.1" 200 239 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:41:41.9842 Timing out client: IPv6Address(type='TCP', host='::ffff:192.168.178.20', port=45336, flowInfo=0, scopeID=0)
07:41:41.9848 Timing out client: IPv6Address(type='TCP', host='::ffff:192.168.178.20', port=45324, flowInfo=0, scopeID=0)
07:41:42.0058 "::ffff:192.168.178.20" - - [14/Sep/2022:05:41:41 +0000] "GET /serienrecorderui/assets/Home.c23d72c1.js HTTP/1.1" 200 4825 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:41:42.0200 "::ffff:192.168.178.20" - - [14/Sep/2022:05:41:41 +0000] "GET /serienrecorderui/assets/Home.c23d72c1.js HTTP/1.1" 200 4825 "http://e4hdultra/serienrecorderui/assets/index.ec6f6fe4.js" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:41:42.0434 "::ffff:192.168.178.20" - - [14/Sep/2022:05:41:41 +0000] "GET /serienrecorderui/assets/Home.c23d72c1.js HTTP/1.1" 206 4825 "http://e4hdultra/serienrecorderui/assets/index.ec6f6fe4.js" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:41:42.1513 "::ffff:192.168.178.20" - - [14/Sep/2022:05:41:41 +0000] "GET /serienrecorderui/favicon.ico HTTP/1.1" 200 4030 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:41:44.8706 "::ffff:192.168.178.20" - - [14/Sep/2022:05:41:41 +0000] "GET /api/pipinfo?_=1663134039989 HTTP/1.1" 200 33 "http://e4hdultra/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:41:44.8774 [eConsoleAppContainer] Starting /usr/bin/grab
07:41:45.0962 "::ffff:192.168.178.20" - - [14/Sep/2022:05:41:44 +0000] "GET /grab?format=jpg&mode=all&t=1663134103671 HTTP/1.1" 200 355411 "http://e4hdultra/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:42:15.8859 "::ffff:192.168.178.20" - - [14/Sep/2022:05:42:12 +0000] "GET /api/pipinfo?_=1663134039990 HTTP/1.1" 200 33 "http://e4hdultra/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:42:15.9034 [eConsoleAppContainer] Starting /usr/bin/grab
07:42:16.1136 "::ffff:192.168.178.20" - - [14/Sep/2022:05:42:15 +0000] "GET /grab?format=jpg&mode=all&t=1663134134693 HTTP/1.1" 200 377187 "http://e4hdultra/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:42:46.8941 "::ffff:192.168.178.20" - - [14/Sep/2022:05:42:43 +0000] "GET /api/pipinfo?_=1663134039991 HTTP/1.1" 200 33 "http://e4hdultra/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:42:46.8953 Timing out client: IPv6Address(type='TCP', host='::ffff:192.168.178.20', port=50096, flowInfo=0, scopeID=0)
07:42:46.9209 [eConsoleAppContainer] Starting /usr/bin/grab
07:42:47.1387 "::ffff:192.168.178.20" - - [14/Sep/2022:05:42:46 +0000] "GET /grab?format=jpg&mode=all&t=1663134165713 HTTP/1.1" 200 354170 "http://e4hdultra/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:43:17.8795 "::ffff:192.168.178.20" - - [14/Sep/2022:05:43:15 +0000] "GET /api/pipinfo?_=1663134039992 HTTP/1.1" 200 33 "http://e4hdultra/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:43:17.8900 [eConsoleAppContainer] Starting /usr/bin/grab
07:43:18.1136 "::ffff:192.168.178.20" - - [14/Sep/2022:05:43:17 +0000] "GET /grab?format=jpg&mode=all&t=1663134196733 HTTP/1.1" 200 384296 "http://e4hdultra/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:43:33.0792 [AutoTimer] current auto poll 2022-09-14 07:43:33
07:43:33.0795 [AutoTimer] Auto Poll Started
07:43:33.0837 job Components.Task.Job name=AutoTimer #tasks=0 completed with [] in None
07:43:33.0841 [AutoTimer] next auto poll at 2022-09-14 11:43:33
07:43:48.8844 "::ffff:192.168.178.20" - - [14/Sep/2022:05:43:45 +0000] "GET /api/pipinfo?_=1663134039993 HTTP/1.1" 200 33 "http://e4hdultra/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:43:48.8962 [eConsoleAppContainer] Starting /usr/bin/grab
07:43:49.1167 "::ffff:192.168.178.20" - - [14/Sep/2022:05:43:48 +0000] "GET /grab?format=jpg&mode=all&t=1663134227749 HTTP/1.1" 200 338788 "http://e4hdultra/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:43:58.5104 "::ffff:192.168.178.20" - - [14/Sep/2022:05:43:58 +0000] "GET /serienrecorderui/assets/Log.3e8c44af.css HTTP/1.1" 200 119 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:43:58.5264 "::ffff:192.168.178.20" - - [14/Sep/2022:05:43:58 +0000] "GET /serienrecorderui/assets/Log.185f5e16.js HTTP/1.1" 200 1273 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:43:58.5451 "::ffff:192.168.178.20" - - [14/Sep/2022:05:43:58 +0000] "GET /serienrecorderui/assets/Log.185f5e16.js HTTP/1.1" 206 1273 "http://e4hdultra/serienrecorderui/assets/index.ec6f6fe4.js" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:43:58.5944 [SerienRecorder] ApiGetLog
07:43:58.5946 {}
07:43:58.5952 [SerienRecorder] ApiBaseResource (returnResult)
07:43:58.5953 [SerienRecorder] URI: [/serienrecorderapi/log] / Args: [{}] / Content: [] 
07:43:58.5974 "::ffff:192.168.178.20" - - [14/Sep/2022:05:43:58 +0000] "GET /serienrecorderapi/log HTTP/1.1" 200 2743 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:12.5118 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:11 +0000] "GET /serienrecorderui/assets/Markers.3a8b28e0.css HTTP/1.1" 200 609 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:12.5617 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:11 +0000] "GET /serienrecorderui/assets/Markers.0cade41f.js HTTP/1.1" 200 48536 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:12.5842 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:11 +0000] "GET /serienrecorderui/assets/de.95699913.js HTTP/1.1" 200 7744 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:12.5957 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:11 +0000] "GET /serienrecorderui/assets/SeriesInformationModal.5d7826a0.js HTTP/1.1" 200 2751 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:12.6078 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:11 +0000] "GET /serienrecorderui/assets/Markers.0cade41f.js HTTP/1.1" 200 48536 "http://e4hdultra/serienrecorderui/assets/index.ec6f6fe4.js" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:12.6724 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:11 +0000] "GET /serienrecorderui/assets/de.95699913.js HTTP/1.1" 200 7744 "http://e4hdultra/serienrecorderui/assets/Markers.0cade41f.js" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:12.6823 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:11 +0000] "GET /serienrecorderui/assets/SeriesInformationModal.5d7826a0.js HTTP/1.1" 200 2751 "http://e4hdultra/serienrecorderui/assets/Markers.0cade41f.js" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:12.8424 [SerienRecorder] ApiGetMarkers
07:44:12.8426 {}
07:44:12.8629 [SerienRecorder] ApiBaseResource (returnResult)
07:44:12.8631 [SerienRecorder] URI: [/serienrecorderapi/markers] / Args: [{}] / Content: [] 
07:44:12.8675 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:11 +0000] "GET /serienrecorderapi/markers HTTP/1.1" 200 5716 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:12.9107 [SerienRecorder] ApiGetCover
07:44:12.9108 {b'fsid': [b'better-call-saul']}
07:44:12.9124 [SerienRecorder] ApiImageResource (returnResult)
07:44:12.9126 /media/hdd/SR_Cover/better-call-saul.jpg
07:44:12.9190 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:11 +0000] "GET /serienrecorderapi/cover?fsid=better-call-saul HTTP/1.1" 200 53776 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:12.9240 [SerienRecorder] ApiGetCover
07:44:12.9242 {b'fsid': [b'inside-star-trek']}
07:44:12.9246 [SerienRecorder] ApiImageResource (returnResult)
07:44:12.9246 /media/hdd/SR_Cover/inside-star-trek.jpg
07:44:12.9303 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:12 +0000] "GET /serienrecorderapi/cover?fsid=inside-star-trek HTTP/1.1" 200 38252 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:12.9380 [SerienRecorder] ApiGetCover
07:44:12.9381 {b'fsid': [b'nano']}
07:44:12.9385 [SerienRecorder] ApiImageResource (returnResult)
07:44:12.9386 /media/hdd/SR_Cover/nano.jpg
07:44:12.9435 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:12 +0000] "GET /serienrecorderapi/cover?fsid=nano HTTP/1.1" 200 24131 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:12.9519 [SerienRecorder] ApiGetCover
07:44:12.9521 {b'fsid': [b'star-trek-discovery']}
07:44:12.9525 [SerienRecorder] ApiImageResource (returnResult)
07:44:12.9525 /media/hdd/SR_Cover/star-trek-discovery.jpg
07:44:12.9579 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:12 +0000] "GET /serienrecorderapi/cover?fsid=star-trek-discovery HTTP/1.1" 200 63547 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:12.9709 [SerienRecorder] ApiGetCover
07:44:12.9711 {b'fsid': [b'star-trek-lower-decks']}
07:44:12.9715 [SerienRecorder] ApiImageResource (returnResult)
07:44:12.9716 /usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/images/1x1#FFFFFF.png
07:44:12.9749 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:12 +0000] "GET /serienrecorderapi/cover?fsid=star-trek-lower-decks HTTP/1.1" 200 91 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:13.0046 [SerienRecorder] ApiGetCover
07:44:13.0048 {b'fsid': [b'star-trek-picard']}
07:44:13.0057 [SerienRecorder] ApiImageResource (returnResult)
07:44:13.0058 /media/hdd/SR_Cover/star-trek-picard.jpg
07:44:13.0123 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:12 +0000] "GET /serienrecorderapi/cover?fsid=star-trek-picard HTTP/1.1" 200 44595 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:13.0193 [SerienRecorder] ApiGetCover
07:44:13.0195 {b'fsid': [b'the-neighborhood']}
07:44:13.0199 [SerienRecorder] ApiImageResource (returnResult)
07:44:13.0199 /media/hdd/SR_Cover/the-neighborhood.jpg
07:44:13.0255 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:12 +0000] "GET /serienrecorderapi/cover?fsid=the-neighborhood HTTP/1.1" 200 58187 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:13.0300 [SerienRecorder] ApiGetCover
07:44:13.0302 {b'fsid': [b'star-trek-strange-new-worlds']}
07:44:13.0306 [SerienRecorder] ApiImageResource (returnResult)
07:44:13.0306 /usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/images/1x1#FFFFFF.png
07:44:13.0323 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:12 +0000] "GET /serienrecorderapi/cover?fsid=star-trek-strange-new-worlds HTTP/1.1" 200 91 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:13.0377 [SerienRecorder] ApiGetCover
07:44:13.0379 {b'fsid': [b'star-trek-prodigy']}
07:44:13.0383 [SerienRecorder] ApiImageResource (returnResult)
07:44:13.0383 /media/hdd/SR_Cover/star-trek-prodigy.jpg
07:44:13.0439 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:12 +0000] "GET /serienrecorderapi/cover?fsid=star-trek-prodigy HTTP/1.1" 200 61222 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:19.8974 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:18 +0000] "GET /api/pipinfo?_=1663134039994 HTTP/1.1" 200 33 "http://e4hdultra/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:19.9026 [eConsoleAppContainer] Starting /usr/bin/grab
07:44:20.1222 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:19 +0000] "GET /grab?format=jpg&mode=all&t=1663134258769 HTTP/1.1" 200 294243 "http://e4hdultra/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:23.2514 [SerienRecorder] ApiGetTransmissions
07:44:23.2518 {b'wlid': [b'26270'], b'fsid': [b'better-call-saul'], b'filterMode': [b'2']}
07:44:23.2596 [SerienRecorder] doGetTransmissions [26270] (0) [3sat, Anixe+, ARD alpha, arte, ATV, ATV2, BILD, Boomerang, BR Fernsehen, Cartoon Network, Comedy Central, Crime + Investigation, Curiosity Channel powered by SPIEGEL, Das Erste, DAZN 1, DAZN 2, Deluxe Music, Deutsches Musik Fernsehen, Disney Channel, DMAX, Eurosport 1, Heimatkanal, HGTV, hr-Fernsehen, Junior, Kabel Eins, Kabel Eins Classics, Kabel Eins Doku, KiKA, Lilo TV, MDR, More Than Sports TV, Motorvision TV, MTV, N24 Doku, Nicktoons, ntv, One, ORF 1, ORF 2, ORF III, Phoenix, ProSieben, ProSieben MAXX, ProSieben Schweiz, RiC, Romance TV, RTL, RTL Zwei, RTLup, Sat.1, Sat.1 Emotions, Sat.1 Gold, ServusTV Deutschland, sixx, Sky Atlantic, Sky Cinema Action, Sky Cinema Best of, Sky Cinema Classics, Sky Cinema Family, Sky Cinema Fun, Sky Cinema Premieren, Sky Cinema Premieren +24, Sky Cinema Thriller HD, Sky Comedy, Sky Crime, Sky Documentaries, Sky Krimi, Sky Nature, Sky One, Sky Replay, Sky Sport 1, Sky Sport 2, Sky Sport Bundesliga 1, Sky Sport Bundesliga HD, Sky Sport Golf HD, Sky Sport Mix HD, Sky Sport News, Sky Sport Premier League HD, Sky Sport Tennis HD, Sky Sport Top Event, Sky Sport UHD, Spiegel Geschichte, Sport1, Super RTL, SYFY, tagesschau24, Tele 5, TLC, TOGGO plus, TV5 Monde, Universal TV, VOX, VOXup, Warner TV Comedy, Warner TV Film, Warner TV Serie, WDR, wedo movies, WELT, Welt der Wunder TV, ZDF, ZDFinfo, ZDFneo]
07:44:23.4582 [SerienRecorder] ApiBaseResource (returnResult)
07:44:23.4584 [SerienRecorder] URI: [/serienrecorderapi/transmissions?wlid=26270&fsid=better-call-saul&filterMode=2] / Args: [{b'wlid': [b'26270'], b'fsid': [b'better-call-saul'], b'filterMode': [b'2']}] / Content: [] 
07:44:23.4619 "::ffff:192.168.178.20" - - [14/Sep/2022:05:44:19 +0000] "GET /serienrecorderapi/transmissions?wlid=26270&fsid=better-call-saul&filterMode=2 HTTP/1.1" 200 1005 "http://e4hdultra/serienrecorderui/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
07:44:33.1741 [SerienRecorder] ApiCreateTimer
07:44:33.1744 b'{"wlid":"26270","fsid":"better-call-saul","name":"Better Call Saul","filterMode":2,"transmissions":[{"channel":"ZDF","endTime":1663552200,"episode":"07","season":"5","startTime":1663549500,"title":"JMM","type":0}]}'
07:44:33.1753 ---------' Manuelle Timererstellung aus Sendeterminen um 14.09.2022 - 07:44:33 '---------
07:44:33.1818 [SerienRecorder] Check configured recording directories
07:44:33.3294 Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.9/site-packages/twisted/web/http.py", line 1767, in dataReceived
	    
	  File "/usr/lib/python3.9/site-packages/twisted/web/http.py", line 2258, in _finishRequestBody
	    
	  File "/usr/lib/python3.9/site-packages/twisted/web/http.py", line 2369, in allContentReceived
	    
	  File "/usr/lib/python3.9/site-packages/twisted/web/http.py", line 1003, in requestReceived
	    
	--- <exception caught here> ---
	  File "/usr/lib/python3.9/site-packages/twisted/web/server.py", line 229, in process
	    
	  File "/usr/lib/python3.9/site-packages/twisted/web/server.py", line 294, in render
	    
	  File "/usr/lib/python3.9/site-packages/twisted/web/resource.py", line 263, in render
	    
	  File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorderResource.py", line 1638, in render_POST
	    (activatedTimer, deactivatedTimer) = serienRecSendeTermine.prepareTimer(database, data['filterMode'], data['wlid'], data['fsid'], transmissions)
	  File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorderTransmissionsScreen.py", line 570, in prepareTimer
	    (count_manually, count_primary_bouquet, count_secondary_bouquet) = database.getNumberOfTimersByBouquet(fsid, str(staffel), str(episode))
	  File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorderDatabase.py", line 1241, in getNumberOfTimersByBouquet
	    if primary_bouquet > 0:
	builtins.TypeError: '>' not supported between instances of 'NoneType' and 'int'
	
```
Hier auch mal die Datenbank: https://www.dropbox.com/s/m7hpg5ivhmylc2r/SerienRecorder.db?dl=1

Ich habe versucht im WebIF einen Timer manuell anzulegen. Der Fehler ist der gleiche. Da scheint irgendwo 'None' als Wert zu kommen
Brauchst Du noch mehr?

**Comment by MacDisein** [comment]
Als Workaround könntest du die Option "Standard Bouquet bevorzugen" in den Einstellungen deaktivieren, die Option macht eh nur Sinn, wenn man alternative Sender in der Senderzuordnung zugewiesen hat.

**Comment by MegaV0lt** [comment]
Ok, mit der deaktivierten Option werden Timer erstellt. Vielen Dank!

Angenommen ich definiere einen oder mehrere alternative Sender, würde es dann auch wieder mit aktivierter Option funktionieren?

**Comment by MegaV0lt** [comment]
Ok, hab ich dann falsch verstanden. Dachte es ist falls ein Kanal nicht aufgenommen werden kann, weil zu wenig tuner frei sing...

Kannst Du einen Workaround einbauen, damit das Problem nicht bei anderen auftritt?

**Comment by MacDisein** [comment]
Ja, ein Bugfix kommt auf jeden Fall mit der nächsten Betaversion.
Danke fürs Melden!
